-- Criação da tabela de postagens no Supabase (PostgreSQL)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thumb_image TEXT,
    thumb_image_alt_text VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    profile_thumb_image VARCHAR(255),
    profile_name VARCHAR(255) NOT NULL,
    post_date VARCHAR(50),
    category VARCHAR(50) DEFAULT 'general',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS (Row Level Security) e permitir leitura/escrita pública anônima para esta demonstração
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura pública"
    ON public.posts FOR SELECT
    USING (true);

CREATE POLICY "Permitir inserção pública"
    ON public.posts FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Permitir atualização pública"
    ON public.posts FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Permitir deleção pública"
    ON public.posts FOR DELETE
    USING (true);

-- Dados iniciais (Seed) baseados nos mocks originais da API
INSERT INTO public.posts (thumb_image, thumb_image_alt_text, title, description, profile_thumb_image, profile_name, post_date, category)
VALUES
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Google',
    'Google Notícias completa 20 anos com redesign e fundo de apoio ao jornalismo independente',
    'Na última semana, o Google apresentou uma nova versão para desktop do seu serviço de notícias. Após um redesign profundo, o Google Notícias promete informar mais sobre os temas que os usuários acompanham, com mais profundidade e facilidade de acesso – seja lendo no smartphone ou, agora, no computador.',
    '/images/profile-1.jpg',
    'Fernando Silva',
    '1/03/2022',
    'tecnologia'
),
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Apple',
    'Vendas do Macbook Pro com chip M2 começam nesta sexta-feira (24)',
    'Durante a WWDC deste ano, a Apple anunciou diversas novidades em seus sistemas e produtos, incluindo um Macbook Air redesenhado e com a segunda geração de chips da empresa, o M2.',
    '/images/profile-2.jpg',
    'Paula Ramos',
    '1/03/2022',
    'tecnologia'
),
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Carros',
    'Citroen Ami Buggy: O carro mais simpático que você já viu até hoje',
    '17 minutos para esgotar e apenas 2 minutos e 53 segundos para vender a primeira unidade. Estes são os números (incríveis) das vendas das 50 unidades especiais e ultra limitadas do My Ami Buggy, da Citroen.',
    '/images/profile-3.jpg',
    'Rodrigo Silveira',
    '1/03/2022',
    'carros'
),
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Games',
    'SEGA anuncia Hyenas, novo FPS no espaço pós-apocalíptico',
    'O mundo dos jogos competitivos nunca foi tão diverso, e o anúncio feito pela SEGA nesta quarta-feira (22) promete contribuir com outro título promissor.',
    '/images/profile-4.jpg',
    'Lucas Oliveira',
    '10/06/2022',
    'games'
),
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Metaverso',
    'Metaverso explode em discussões na internet, mas público ainda tem receios',
    'De acordo com números consolidados pela Comscore, apenas 24% dos comentários da internet sobre o metaverso são positivos. O motivo, por sua vez, seria o desconhecimento do público acerca do assunto, que ainda desperta dúvidas e receios em muita gente.',
    '/images/profile-1.jpg',
    'Maria Silva',
    '10/06/2022',
    'tecnologia'
),
(
    'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2023/02/221223090506-01-bugatti-chiron-profilee.jpg',
    'Web3',
    'Como o metaverso e a web3 revolucionarão a vida e os negócios?',
    'A ideia de criar mundos inteiramente fictícios e com possibilidades infinitas sempre encantou o ser humano. Seja nas antigas tradições orais, na literatura, nas telas do cinema ou nos jogos, mais recentemente, o desejo pela materialização daquilo que somente a criatividade e a mente podem elaborar move montanhas, além de muito dinheiro.',
    '/images/profile-2.jpg',
    'Debora Pacheco',
    '10/06/2022',
    'tecnologia'
);
